# Dependencies
markdown:         GFM
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Yuntao Li
tagline:          'Homepage'
description:      'Code; Model; Learn'
url:              'physcoder.github.io'
baseurl:          /

author:
  name:           'Yuntao Li'
  url:            https://www.linkedin.com/in/yuntaoli/

paginate:         5

# Custom vars
# version:          2.1.0
# github:
#   repo:           https://github.com/poole/hyde
