# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Yuntao
tagline:          'Homepage'
description:      'Code, Model, Learn'
url:              'http://physcoder.github.io'
baseurl:          "http://physcoder.github.io/" # for local testing, change to "/"

author:
  name:           'Yuntao'
  url:            https://www.linkedin.com/in/yuntaoli/

paginate:         5 # how many post to display per page

# Custom vars
# version:          2.1.0
# github:
#   repo:           https://github.com/poole/hyde
