# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Yuntao Li
tagline:          'Homepage'
description:      'Code, Model, Learn'
url:              'http://physcoder.github.io'
baseurl:          "http://physcoder.github.io/"

author:
  name:           'Yuntao Li'
  url:            https://www.linkedin.com/in/yuntaoli/

paginate:         5

# Custom vars
# version:          2.1.0
# github:
#   repo:           https://github.com/poole/hyde
